name: Wookieleaks
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9419242f-0a05-4415-8fc0-523e4348371b.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f51efaa6-8dd5-4c08-b8e5-89b6b5b6a719.jpg
layout_spectrum: 0.20831299438371814
typography_spectrum: 0.03363501615241391
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#A9602B'
    - '#CB823E'
    - '#7A3D1E'
    - '#E6A45A'
    - '#DFC9BC'
  brandStrength: 0.29734471043313637
  lightness: 0.8312966078719917
  saturation: 0.26171189738372985
  rhythmicContrast: 0.40896148990129705
purpose:
  - type: external
    label: swgoh.gg
    url: 'https://swgoh.gg/g/24495/wookieleaks/'
  - type: external
    label: discord
    url: 'https://discord.gg/zkBsbju'
title: ''
description: ''
author:
  name: Wookieleaks Command
  url: 'http://wookieleaks.xyz'
content_rating:
  adult: false
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/afe1a221-d10c-4ee2-8a72-0be64d8619c5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/afe1a221-d10c-4ee2-8a72-0be64d8619c5.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/afe1a221-d10c-4ee2-8a72-0be64d8619c5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/afe1a221-d10c-4ee2-8a72-0be64d8619c5.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
analytics:
  google: UA-108283677-1
